### ISSUE TITLE
Assalomu Aleykum, shu joyida position qilish kerak edi

### ISSUE THREAD

**Issue by SayramovAzizbek** [JumabaevZiyodilla/book#2]
Assalomu Aleykum, shu joyida agar after qilgan bo'lsangiz position absolute bn li ni width bo'yicha turishi kerak sizda ikki yonda li ga padding berganiz uchun bergan after ringiz ohirgacham yetmay qolgan sagar shuni qilib qo'ysangiz juda chiroyli chiqqan bo'lar edi
![image](https://user-images.githubusercontent.com/96992119/176833051-7e306215-0d1e-4ab4-bfd0-f3fe57903b85.png)

**Comment by JumabaevZiyodilla** [comment]
Done
